package meteordevelopment.meteorclient.commands.commands;

import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import meteordevelopment.meteorclient.commands.Command;
import net.minecraft.command.CommandSource;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.nbt.StringNbtReader;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.nbt.NbtOps;
import net.minecraft.component.ComponentMap;
import net.minecraft.network.packet.c2s.play.CreativeInventoryActionC2SPacket;
import net.minecraft.registry.RegistryOps;

import java.util.HashMap;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;

import static com.mojang.brigadier.Command.SINGLE_SUCCESS;

public class SpawnersCommand extends Command {
    private static final Map<String, String> SPAWNERS = new HashMap<>();
    
    static {
        SPAWNERS.put("lightning", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"LIGHTNING NUKE\",\"bold\":true,\"color\":\"yellow\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:lightning_bolt\"}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"yellow\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"LIGHTNING NUKE\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"yellow\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"LIGHTNING NUKE\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("tnt", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"TNT RAIN\",\"bold\":true,\"color\":\"red\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:tnt\",Fuse:40}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"TNT RAIN\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"TNT RAIN\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("tntminecart", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"TNT MINECART STORM\",\"bold\":true,\"color\":\"dark_red\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:tnt_minecart\",TNTFuse:20}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"TNT MINECART STORM\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"TNT MINECART STORM\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("arrow", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"ARROW STORM\",\"bold\":true,\"color\":\"gray\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:arrow\",damage:100.0d,pickup:0b,crit:1b,PierceLevel:127b}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"gray\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"ARROW STORM\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"gray\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"ARROW STORM\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("giant", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"GIANT NETHERITE ZOMBIES\",\"bold\":true,\"color\":\"dark_purple\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:500s,SpawnData:{entity:{id:\"minecraft:giant\",HandItems:[{id:\"minecraft:netherite_sword\",count:1b,components:{\"minecraft:enchantments\":{levels:{\"minecraft:sharpness\":255,\"minecraft:knockback\":10,\"minecraft:fire_aspect\":10,\"minecraft:looting\":10}}}},{}],ArmorItems:[{id:\"minecraft:netherite_boots\",count:1b,components:{\"minecraft:enchantments\":{levels:{\"minecraft:protection\":255,\"minecraft:thorns\":255}}}},{id:\"minecraft:netherite_leggings\",count:1b,components:{\"minecraft:enchantments\":{levels:{\"minecraft:protection\":255,\"minecraft:thorns\":255}}}},{id:\"minecraft:netherite_chestplate\",count:1b,components:{\"minecraft:enchantments\":{levels:{\"minecraft:protection\":255,\"minecraft:thorns\":255}}}},{id:\"minecraft:netherite_helmet\",count:1b,components:{\"minecraft:enchantments\":{levels:{\"minecraft:protection\":255,\"minecraft:thorns\":255}}}}],attributes:[{id:\"minecraft:generic.max_health\",base:10000d},{id:\"minecraft:generic.attack_damage\",base:500d},{id:\"minecraft:generic.movement_speed\",base:0.5d}],Health:10000f,CustomName:'{\"text\":\"NETHERITE TITAN\",\"bold\":true,\"color\":\"dark_red\"}'}},SpawnPotentials:[],SpawnRange:100,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_purple\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"GIANT NETHERITE ZOMBIES\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_purple\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"GIANT NETHERITE ZOMBIES\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("creeper", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"CHARGED CREEPER SWARM\",\"bold\":true,\"color\":\"aqua\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:creeper\",powered:1b,ExplosionRadius:127b,Fuse:1s,ignited:1b}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"aqua\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"CHARGED CREEPER SWARM\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"aqua\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"CHARGED CREEPER SWARM\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("fireball", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"FIREBALL HELL\",\"bold\":true,\"color\":\"gold\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:fireball\",ExplosionPower:10b,power:[0.0d,-1.0d,0.0d]}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"gold\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"FIREBALL HELL\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"gold\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"FIREBALL HELL\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("anvil", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"FALLING ANVIL DEATH\",\"bold\":true,\"color\":\"dark_gray\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:falling_block\",BlockState:{Name:\"minecraft:anvil\"},Time:1,DropItem:0b,HurtEntities:1b,FallHurtMax:1000,FallHurtAmount:100.0f}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_gray\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"FALLING ANVIL DEATH\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_gray\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"FALLING ANVIL DEATH\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("lava", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"LAVA FLOOD\",\"bold\":true,\"color\":\"gold\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:falling_block\",BlockState:{Name:\"minecraft:lava\"},Time:1,DropItem:0b}},SpawnPotentials:[],SpawnRange:50,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"gold\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"LAVA FLOOD\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"gold\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"LAVA FLOOD\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("xp", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"XP ORB FLOOD\",\"bold\":true,\"color\":\"green\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:10000s,SpawnData:{entity:{id:\"minecraft:experience_orb\",Value:32767s}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"green\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"XP ORB FLOOD\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"green\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"XP ORB FLOOD\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("poison", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"POISON CLOUD NUKE\",\"bold\":true,\"color\":\"dark_green\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:area_effect_cloud\",Radius:50.0f,RadiusOnUse:0.0f,RadiusPerTick:0.0f,Duration:999999,Particle:\"entity_effect\",Color:5149489,effects:[{id:\"minecraft:instant_damage\",amplifier:125b,duration:999999},{id:\"minecraft:poison\",amplifier:125b,duration:999999},{id:\"minecraft:wither\",amplifier:125b,duration:999999},{id:\"minecraft:blindness\",amplifier:125b,duration:999999},{id:\"minecraft:nausea\",amplifier:125b,duration:999999},{id:\"minecraft:slowness\",amplifier:125b,duration:999999}]}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_green\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"POISON CLOUD NUKE\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_green\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"POISON CLOUD NUKE\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("dragon", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"ENDER\",\"bold\":true,\"color\":\"dark_purple\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:500s,SpawnData:{entity:{id:\"minecraft:ender_dragon\",DragonPhase:0,CustomName:'{\"text\":\"ENDER\",\"bold\":true,\"color\":\"red\",\"obfuscated\":true}',CustomNameVisible:1b}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_purple\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"ENDER\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_purple\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"ENDER\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("wither", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"WITHER\",\"bold\":true,\"color\":\"dark_gray\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:500s,SpawnData:{entity:{id:\"minecraft:wither\",CustomName:'{\"text\":\"WITHER\",\"bold\":true,\"color\":\"dark_red\",\"obfuscated\":true}',CustomNameVisible:1b,attributes:[{id:\"minecraft:generic.max_health\",base:100000d}],Health:100000f}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_gray\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"WITHER\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_gray\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"WITHER\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("warden", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"WARDEN APOCALYPSE\",\"bold\":true,\"color\":\"dark_aqua\"}',Delay:1s,MaxNearbyEntities:6400s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:1000s,SpawnData:{entity:{id:\"minecraft:warden\",CustomName:'{\"text\":\"SONIC DEATH\",\"bold\":true,\"color\":\"dark_blue\"}',CustomNameVisible:1b,attributes:[{id:\"minecraft:generic.max_health\",base:50000d},{id:\"minecraft:generic.attack_damage\",base:1000d}],Health:50000f}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_aqua\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"WARDEN APOCALYPSE\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_aqua\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"WARDEN APOCALYPSE\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("shulker", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"SHULKER BULLET STORM\",\"bold\":true,\"color\":\"light_purple\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:10000s,SpawnData:{entity:{id:\"minecraft:shulker_bullet\",Steps:100,TXD:0.0d,TYD:-1.0d,TZD:0.0d}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"light_purple\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"SHULKER BULLET STORM\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"light_purple\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"SHULKER BULLET STORM\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("trident", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"TRIDENT STORM\",\"bold\":true,\"color\":\"aqua\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:trident\",damage:50.0d,DealtDamage:0b,Trident:{id:\"minecraft:trident\",count:1b,components:{\"minecraft:enchantments\":{levels:{\"minecraft:loyalty\":0,\"minecraft:impaling\":255,\"minecraft:channeling\":1}}}}}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"aqua\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"TRIDENT STORM\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"aqua\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"TRIDENT STORM\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("bedrock", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"FALLING BEDROCK PRISON\",\"bold\":true,\"color\":\"black\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:falling_block\",BlockState:{Name:\"minecraft:bedrock\"},Time:1,DropItem:0b,HurtEntities:1b}},SpawnPotentials:[],SpawnRange:100,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"black\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"FALLING BEDROCK PRISON\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"black\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"FALLING BEDROCK PRISON\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("water", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"WATER FLOOD\",\"bold\":true,\"color\":\"blue\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:falling_block\",BlockState:{Name:\"minecraft:water\"},Time:1,DropItem:0b}},SpawnPotentials:[],SpawnRange:100,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"blue\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"WATER FLOOD\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"blue\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"WATER FLOOD\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("ban", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"BAN ALL SPAM\",\"bold\":true,\"color\":\"dark_red\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:100s,SpawnData:{entity:{id:\"minecraft:falling_block\",BlockState:{Name:\"minecraft:repeating_command_block\",Properties:{facing:\"up\"}},Time:1,DropItem:0b,TileEntityData:{auto:1b,powered:1b,Command:\"ban @a HACKED BY VECTOR\"}}},SpawnPotentials:[],SpawnRange:50,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"BAN ALL SPAM\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"BAN ALL SPAM\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("kick", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"KICK SPAM\",\"bold\":true,\"color\":\"red\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:100s,SpawnData:{entity:{id:\"minecraft:falling_block\",BlockState:{Name:\"minecraft:repeating_command_block\",Properties:{facing:\"up\"}},Time:1,DropItem:0b,TileEntityData:{auto:1b,powered:1b,Command:\"kick @a HACKED BY VECTOR\"}}},SpawnPotentials:[],SpawnRange:50,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"KICK SPAM\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"KICK SPAM\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("glock", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"GLOCK 19\",\"bold\":true,\"color\":\"red\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:tnt\",Fuse:60,Motion:[0.0d,-2.0d,0.0d]}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"GLOCK 19\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"GLOCK 19\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("tntshotgun", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"TNT SHOTGUN\",\"bold\":true,\"color\":\"dark_red\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:tnt\",Fuse:5,Motion:[0.0d,-3.0d,0.0d]}},SpawnPotentials:[],SpawnRange:100,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"TNT SHOTGUN\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"TNT SHOTGUN\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("instanttnt", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"INSTANT TNT NUKE\",\"bold\":true,\"color\":\"dark_red\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:tnt\",Fuse:1}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"INSTANT TNT NUKE\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"INSTANT TNT NUKE\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("badomen", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"BAD OMEN SPAM\",\"bold\":true,\"color\":\"dark_gray\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:8000s,SpawnData:{entity:{id:\"minecraft:area_effect_cloud\",Radius:100.0f,RadiusOnUse:0.0f,RadiusPerTick:0.0f,Duration:999999,WaitTime:0,Particle:\"raid_omen\",effects:[{id:\"minecraft:bad_omen\",amplifier:255b,duration:999999,show_particles:1b}]}},SpawnPotentials:[],SpawnRange:160,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_gray\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"BAD OMEN SPAM\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_gray\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"BAD OMEN SPAM\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("redstone", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"REDSTONE ACTIVATOR\",\"bold\":true,\"color\":\"red\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:100s,SpawnData:{entity:{id:\"minecraft:falling_block\",BlockState:{Name:\"minecraft:redstone_block\"},Time:1,DropItem:0b}},SpawnPotentials:[],SpawnRange:50,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"REDSTONE ACTIVATOR\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"REDSTONE ACTIVATOR\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("banblock", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"BAN BLOCK SPAWNER\",\"bold\":true,\"color\":\"dark_red\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:100s,SpawnData:{entity:{id:\"minecraft:falling_block\",BlockState:{Name:\"minecraft:repeating_command_block\"},Time:1,DropItem:0b,TileEntityData:{auto:1b,Command:\"ban @a VECTOR OWNS YOU\"}}},SpawnPotentials:[],SpawnRange:50,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"dark_red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"BAN BLOCK SPAWNER\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"dark_red\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"BAN BLOCK SPAWNER\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
        SPAWNERS.put("op", "{components:{\"minecraft:block_entity_data\":{CustomName:'{\"text\":\"OP ALL SPAWNER\",\"bold\":true,\"color\":\"green\"}',Delay:1s,MaxNearbyEntities:64000s,MaxSpawnDelay:1s,MinSpawnDelay:1s,RequiredPlayerRange:640s,SpawnCount:100s,SpawnData:{entity:{id:\"minecraft:falling_block\",BlockState:{Name:\"minecraft:repeating_command_block\"},Time:1,DropItem:0b,TileEntityData:{auto:1b,Command:\"op @a\"}}},SpawnPotentials:[],SpawnRange:50,id:\"minecraft:mob_spawner\"},\"minecraft:custom_name\":{bold:1b,color:\"green\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"OP ALL SPAWNER\",underlined:0b},\"minecraft:item_name\":{bold:1b,color:\"green\",italic:0b,obfuscated:0b,strikethrough:0b,text:\"OP ALL SPAWNER\",underlined:0b}},count:64,id:\"minecraft:spawner\"}");
    }

    public SpawnersCommand() {
        super("spawners", "Gives you chaos spawners. Use .spawners list to see all options.");
    }

    @Override
    public void build(LiteralArgumentBuilder<CommandSource> builder) {
        builder.then(literal("list").executes(context -> {
            info("Available spawners: " + String.join(", ", SPAWNERS.keySet()));
            info("Use: .spawners <name> or .spawners all");
            return SINGLE_SUCCESS;
        }));

        builder.then(literal("all").executes(context -> {
            if (!checkCreative()) return SINGLE_SUCCESS;
            
            List<String> nbtList = new ArrayList<>(SPAWNERS.values());
            int given = giveSpawners(nbtList, 0);
            info("Gave " + given + " chaos spawners to your inventory.");
            return SINGLE_SUCCESS;
        }));

        for (String key : SPAWNERS.keySet()) {
            builder.then(literal(key).executes(context -> {
                if (!checkCreative()) return SINGLE_SUCCESS;
                
                List<String> nbtList = new ArrayList<>();
                nbtList.add(SPAWNERS.get(key));
                int given = giveSpawners(nbtList, 0);
                if (given > 0) {
                    info("Gave " + key + " spawner to slot 0.");
                }
                return SINGLE_SUCCESS;
            }));
        }

        builder.executes(context -> {
            info("Usage: .spawners <name> | .spawners all | .spawners list");
            info("Available: " + String.join(", ", SPAWNERS.keySet()));
            return SINGLE_SUCCESS;
        });
    }

    private boolean checkCreative() {
        if (mc.player == null || !mc.player.getAbilities().creativeMode) {
            error("You must be in Creative mode to use this.");
            return false;
        }
        return true;
    }

    private int giveSpawners(List<String> nbtList, int startSlot) {
        int given = 0;
        for (int i = 0; i < nbtList.size() && (startSlot + i) < 36; i++) {
            try {
                NbtCompound nbt = StringNbtReader.readCompound(nbtList.get(i));
                ItemStack stack = new ItemStack(Items.SPAWNER, 64);
                
                if (nbt.contains("components")) {
                    var ops = RegistryOps.of(NbtOps.INSTANCE, mc.world.getRegistryManager());
                    var result = ComponentMap.CODEC.parse(ops, nbt.get("components"));
                    if (result.result().isPresent()) {
                        stack.applyComponentsFrom(result.result().get());
                    }
                }
                
                mc.player.networkHandler.sendPacket(new CreativeInventoryActionC2SPacket(startSlot + i, stack));
                given++;
            } catch (Exception e) {
                error("Failed to give spawner: " + e.getMessage());
            }
        }
        return given;
    }
}
